let allPlatforms=[];let activeTab='all';let deferredInstallPrompt=null;let siteData=null;let inlineEditor=null;let modalReturnFocus=null;
const $=id=>document.getElementById(id);
const STORAGE={favorites:'dunya-favorites-v2',compare:'dunya-platform-compare-v3',compareLegacy:'dunya-compare-v2',views:'dunya-views-v2',recent:'dunya-recent-v2',theme:'dunya-theme-v2'};
const els={search:$('searchInput'),heroSearch:$('heroSearchInput'),grid:$('platformGrid'),featured:$('featuredGrid'),categoryGrid:$('categoryGrid'),filterLang:$('filterLang'),filterCategory:$('filterCategory'),filterPricing:$('filterPricing'),filterVerification:$('filterVerification'),filterFree:$('filterFree'),filterCert:$('filterCert'),sort:$('sortSelect'),compareDock:$('compareDock')};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch(_){return f}}
function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
function getFavorites(){return new Set(readJSON(STORAGE.favorites,[]))}function setFavorites(s){writeJSON(STORAGE.favorites,[...s])}
function getCompare(){return new Set(readJSON(STORAGE.compare,[]))}function setCompare(s){writeJSON(STORAGE.compare,[...s])}
function getViews(){return readJSON(STORAGE.views,{})}
function getRecent(){return readJSON(STORAGE.recent,[]).map((x,i)=>typeof x==='string'?{id:x,ts:Date.now()-i}:x).filter(x=>x&&x.id)}
function maxCompare(){const n=Number(siteData&&siteData.comparison&&siteData.comparison.maxPlatforms);return Number.isInteger(n)&&n>0?n:3}
function emptyValue(){return String(siteData&&siteData.comparison&&siteData.comparison.emptyValue||'')}
function migrateComparisonStorage(){let current=null,hasCurrent=false;try{const raw=localStorage.getItem(STORAGE.compare);hasCurrent=raw!==null;if(hasCurrent)current=JSON.parse(raw)}catch(_){}const legacy=readJSON(STORAGE.compareLegacy,[]);const ids=PlatformDirectory.migrateComparisonIds(hasCurrent&&Array.isArray(current)?current:null,legacy,allPlatforms.map(p=>p.id),maxCompare());setCompare(new Set(ids))}
function platformById(id){return allPlatforms.find(p=>p.id===id)}
function nameFor(p){return content?content.platformName(p):''}
function descriptionFor(p){return content?content.platformDescription(p):''}
function detailUrl(p){return SeoRoutes.platformUrl(p,currentLang)}
function languagesLabel(p){return(p.languageIds||[]).map(id=>content.languageLabel(id)).filter(Boolean).join(' · ')}
function safeExternal(url){return content.safeUrl(url,{allowRelative:false})}
function fallbackLogo(){return content.asset('platformFallbackLogo')}
function logoHtml(p,name){
  const own=p.logo&&p.logo.src?{src:content.safeUrl(p.logo.src,{allowRelative:true}),alt:content.localize(p.logo.alt)}:{src:'',alt:''};
  const logo=own.src?own:fallbackLogo();if(!logo.src)return'';
  return `<img class="platform-logo" src="${esc(logo.src)}" alt="${esc(own.alt||logo.alt||name)}" loading="lazy">`;
}
function populateSelect(el,values,labelFn){if(!el)return;const old=el.value;const all=getText('all');el.innerHTML=(all?`<option value="">${esc(all)}</option>`:'')+values.map(v=>`<option value="${esc(v)}">${esc(labelFn?labelFn(v):v)}</option>`).join('');if(values.includes(old))el.value=old}
function categoryFilterLabel(id){const row=(siteData&&Array.isArray(siteData.categories)?siteData.categories:[]).find(item=>item&&item.id===id);const icon=row&&row.icon?`${row.icon} `:'';return `${icon}${content.categoryLabel(id)}`.trim()}
function hydrateFilterOptions(){const o=PlatformDirectory.getFilterOptions(allPlatforms);const categoryIds=exploreCategoryGroups().map(group=>group.categoryId);populateSelect(els.filterLang,o.languages,id=>content.languageLabel(id));populateSelect(els.filterCategory,categoryIds,id=>categoryFilterLabel(id));populateSelect(els.filterPricing,o.pricingModels,translatePricing);populateSelect(els.filterVerification,['recent','outdated'],translateVerification)}
function renderStats(){const s=PlatformDirectory.getStats(allPlatforms),freeCertificates=allPlatforms.filter(p=>p.freeCertificate===true).length,format=n=>new Intl.NumberFormat('en-US').format(Number(n)||0);$('statPlatforms').textContent=s.platforms;$('statCourses').textContent=`${format(s.courses)}+`;$('statFreeCourses').textContent=`${format(s.freeCourses)}+`;$('statCert').textContent=freeCertificates;$('statLang').textContent=`+${s.languages}`;$('allBadge').textContent=allPlatforms.length;$('favBadge').textContent=getFavorites().size;$('recentBadge').textContent=getRecent().length}
function currentState(){return{query:els.search.value,category:els.filterCategory.value,language:els.filterLang.value,pricingModel:els.filterPricing.value,verification:els.filterVerification.value,freeOnly:els.filterFree.checked,certificateOnly:els.filterCert.checked,sort:['viewed','recent'].includes(els.sort.value)?'recommended':els.sort.value}}
function visiblePlatforms(){const fav=getFavorites(),recent=getRecent(),recentMap=Object.fromEntries(recent.map(x=>[x.id,x.ts]));let list=PlatformDirectory.getVisiblePlatforms(allPlatforms,currentState());if(activeTab==='favorites')list=list.filter(p=>fav.has(p.id));if(activeTab==='recent')list=list.filter(p=>recentMap[p.id]);if(els.sort.value==='viewed'){const views=getViews();list.sort((a,b)=>(views[b.id]||0)-(views[a.id]||0)||nameFor(a).localeCompare(nameFor(b)))}if(els.sort.value==='recent')list.sort((a,b)=>(recentMap[b.id]||0)-(recentMap[a.id]||0));return list}
function fact(label,value){if(!label||!value)return'';return`<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function platformCard(p,compact=false){
  const name=nameFor(p),facts=PlatformDirectory.cardFacts(p),fav=getFavorites().has(p.id),selected=getCompare().has(p.id),official=safeExternal(p.officialUrl);
  const verificationBadge=facts.showVerification?`<span class="verification-badge ${esc(facts.verification)}">${esc(translateVerification(facts.verification))}</span>`:'';
  const certificateKey=PlatformCore.certificateDisplayKey(p),certificateFact=certificateKey?fact(getText('certificate'),getText(certificateKey)):'';
  const count=content.contentCountLabel(p),officialCount=facts.showOfficialCount&&count?`<div class="official-count"><span>${esc(getText('officialContent'))}</span><strong>${esc(count)}</strong></div>`:'';
  const languageFact=fact(getText('language'),languagesLabel(p));
  const compareIcon=content.icon('compare'),shareIcon=content.icon('share'),externalIcon=content.icon('external'),favoriteIcon=content.icon(fav?'favoriteOn':'favoriteOff');
  return `<article class="platform-card${compact?' compact':''}" data-id="${esc(p.id)}"><div class="platform-card-head"><a href="${detailUrl(p)}" class="logo-shell">${logoHtml(p,name)}</a><div class="card-icon-actions"><button class="round-action ${fav?'active':''}" data-action="favorite" data-id="${esc(p.id)}" type="button" aria-pressed="${fav}" aria-label="${esc(fav?getText('removeSaved'):getText('savePlatform'))}">${esc(favoriteIcon)}</button><button class="round-action" data-action="share" data-id="${esc(p.id)}" type="button" aria-label="${esc(getText('sharePlatform'))}">${esc(shareIcon)}</button></div></div><div class="platform-card-body"><div class="badge-row"><span class="tag" data-edit-kind="category" data-edit-id="${esc(p.categoryId)}" data-edit-field="label">${esc(content.categoryLabel(p.categoryId))}</span>${verificationBadge}</div><a class="title-link" href="${detailUrl(p)}"><h3 data-edit-kind="platform" data-edit-id="${esc(p.id)}" data-edit-field="name">${esc(name)}</h3></a>${compact?'':`<p class="platform-desc" data-edit-kind="platform" data-edit-id="${esc(p.id)}" data-edit-field="description">${esc(descriptionFor(p))}</p>`}<div class="fact-grid">${languageFact}${fact(getText('price'),getText(PlatformCore.pricingDisplayKey(p)))}${fact(getText('freeContent'),p.hasFreeContent?getText('yes'):getText('no'))}${certificateFact}</div>${officialCount}<div class="card-actions"><button class="btn-inline ${selected?'active':''}" data-action="compare" data-id="${esc(p.id)}" type="button" aria-pressed="${selected}">${esc(compareIcon)} ${esc(selected?getText('selected'):getText('compare'))}</button><a class="btn-inline" href="${detailUrl(p)}">${esc(getText('details'))}</a>${official?`<a class="btn-inline official" href="${esc(official)}" target="_blank" rel="noopener noreferrer" data-edit-kind="platform" data-edit-id="${esc(p.id)}" data-edit-field="officialUrl">${esc(getText('officialSite'))} ${esc(externalIcon)}</a>`:''}</div></div></article>`;
}
function renderDirectory(){const list=visiblePlatforms();$('resultsCount').textContent=list.length;els.grid.innerHTML=list.length?list.map(p=>platformCard(p)).join(''):`<div class="no-results"><span>${esc(content.icon('search'))}</span> <strong>${esc(getText('noResults'))}</strong></div>`}
function renderFeatured(){const ids=Array.isArray(content.rawSetting('featuredFallbackIds'))?content.rawSetting('featuredFallbackIds'):[];const list=PlatformDirectory.getFeatured(allPlatforms,ids).slice(0,6);els.featured.innerHTML=list.map(p=>platformCard(p,true)).join('')}
function exploreCategoryGroups(){return PlatformDirectory.getCategoryGroups(allPlatforms)}
function renderCategories(){const categoryMap=new Map((siteData.categories||[]).map(row=>[row.id,row]));const groups=exploreCategoryGroups();els.categoryGrid.innerHTML=groups.map(g=>{const row=categoryMap.get(g.categoryId)||{};return`<button class="category-card" type="button" data-category="${esc(g.categoryId)}"><span>${esc(row.icon||'')}</span><strong data-edit-kind="category" data-edit-id="${esc(g.categoryId)}" data-edit-field="label">${esc(content.categoryLabel(g.categoryId))}</strong><small>${g.count}</small></button>`}).join('')}
function renderPlatformCloud(){const box=$('explorePlatformCloud');if(!box)return;const core=box.querySelector('.hero-core');box.querySelectorAll('.platform-cloud-chip').forEach(node=>node.remove());const ids=Array.isArray(content.rawSetting('homePlatformCloud'))?content.rawSetting('homePlatformCloud'):[];ids.map(platformById).filter(Boolean).forEach(p=>{const span=document.createElement('span');span.className='platform-cloud-chip';span.textContent=nameFor(p);box.insertBefore(span,core)})}
function renderQuickFilters(){const box=$('quickFilterChips');if(!box)return;const categoryMap=new Map((siteData.categories||[]).map(row=>[row.id,row]));const groups=exploreCategoryGroups();box.innerHTML=groups.map(g=>{const row=categoryMap.get(g.categoryId)||{};return`<button type="button" data-search-category="${esc(g.categoryId)}">${row.icon?`<span>${esc(row.icon)}</span> `:''}${esc(content.categoryLabel(g.categoryId))}</button>`}).join('')}
function updateCompareDock(){const items=[...getCompare()].map(platformById).filter(Boolean);$('compareCount').textContent=`${items.length}/${maxCompare()}`;$('compareNames').textContent=items.map(nameFor).join(' · ');els.compareDock.classList.toggle('show',items.length>0)}
function rerender(){renderStats();renderFeatured();renderCategories();renderDirectory();updateCompareDock()}
function applyInitialSearch(params){const query=String(params&&typeof params.get==='function'?(params.get('q')||''):'').trim();els.search.value=query;els.heroSearch.value=query;return query}
function focusExploreSection(){
  const section=document.querySelector('#explore');
  if(!section||typeof section.scrollIntoView!=='function')return;
  const focus=()=>section.scrollIntoView({block:'start'});
  if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>requestAnimationFrame(focus));
  else focus();
  if(typeof setTimeout==='function')setTimeout(focus,120);
}
function focusInitialSearchResults(query){if(query)focusExploreSection()}
function focusInitialExploreResults(params){
  const hash=String(location.hash||'');
  const hasCategory=Boolean(params&&typeof params.get==='function'&&(params.get('category')||'').trim());
  if(hash==='#explore'||hasCategory)focusExploreSection();
}
function toggleFavorite(id){const s=getFavorites();s.has(id)?s.delete(id):s.add(id);setFavorites(s);renderStats();renderFeatured();renderDirectory()}
function toggleCompare(id){const result=PlatformCore.toggleComparison([...getCompare()],id,maxCompare());if(result.blocked){showToast(getText('maxCompare'));return}setCompare(new Set(result.ids));updateCompareDock();renderFeatured();renderDirectory()}
async function sharePlatform(id){const p=platformById(id);if(!p)return;const url=new URL(detailUrl(p),location.href).href;try{if(navigator.share)await navigator.share({title:nameFor(p),text:descriptionFor(p),url});else{await navigator.clipboard.writeText(url);showToast(getText('copied'))}}catch(_){}}
function showToast(message){const t=$('toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function openModal(id){const m=$(id);if(!m)return;modalReturnFocus=document.activeElement&&document.activeElement!==document.body?document.activeElement:null;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');const f=m.querySelector('button,a,input,select');if(f)f.focus()}
function closeModal(id){const m=$(id);if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');if(!document.querySelector('.modal.open')){document.body.classList.remove('modal-open');if(modalReturnFocus&&modalReturnFocus.isConnected&&typeof modalReturnFocus.focus==='function')modalReturnFocus.focus();modalReturnFocus=null}}
function buildCompareTable(){
  const rows=PlatformDirectory.comparisonRows([...getCompare()].map(platformById).filter(Boolean));if(!rows.length){$('compareTable').innerHTML='';return}
  const row=(label,fn)=>`<tr><th>${esc(label)}</th>${rows.map(r=>`<td>${fn(r)}</td>`).join('')}</tr>`,empty=esc(emptyValue()),optional=[];
  if(rows.some(r=>r.showOfficialCount))optional.push(row(getText('officialContent'),r=>esc(r.showOfficialCount?content.contentCountLabel(r):emptyValue())));
  if(rows.some(r=>r.showVerification)){optional.push(row(getText('verification'),r=>esc(r.showVerification?translateVerification(r.verification):emptyValue())));optional.push(row(getText('lastVerified'),r=>esc(r.showVerification&&r.lastVerified?r.lastVerified:emptyValue())))}
  $('compareTable').innerHTML=`<table class="compare-table"><thead><tr><th>${esc(getText('compareTitle'))}</th>${rows.map(r=>`<th>${esc(content.localize(r.name))}</th>`).join('')}</tr></thead><tbody>${row(getText('category'),r=>esc(content.categoryLabel(r.categoryId)))}${row(getText('price'),r=>esc(getText(PlatformCore.pricingDisplayKey(r))))}${row(getText('freeContent'),r=>esc(r.hasFreeContent?getText('yes'):getText('no')))}${row(getText('certificate'),r=>{const key=PlatformCore.certificateDisplayKey(r);return esc(key?getText(key):emptyValue())})}${row(getText('language'),r=>esc(r.languageIds.map(id=>content.languageLabel(id)).filter(Boolean).join(' · ')||emptyValue()))}${optional.join('')}${row(getText('bestFor'),r=>esc(content.platformList(r,'bestFor')[0]||emptyValue()))}${row('',r=>{const url=safeExternal(r.officialUrl);return url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(getText('officialSite'))} ${esc(content.icon('external'))}</a>`:empty})}</tbody></table>`;
}
function resetFilters(){els.search.value='';els.heroSearch.value='';els.filterLang.value='';els.filterCategory.value='';els.filterPricing.value='';els.filterVerification.value='';els.filterFree.checked=false;els.filterCert.checked=false;els.sort.value='recommended';activeTab='all';document.querySelectorAll('.tab-btn').forEach(b=>{const active=b.dataset.tab==='all';b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});renderDirectory()}
function applyQuickFilter(id){const item=(siteData.quiz&&siteData.quiz.quickFilters||[]).find(row=>row.id===id);if(!item)return;activeTab='all';if(item.type==='free')els.filterFree.checked=true;else if(item.type==='certificate')els.filterCert.checked=true;else if(item.type==='language')els.filterLang.value=item.targetId||'';else if(item.type==='category')els.filterCategory.value=item.targetId||'';renderDirectory();document.querySelector('#explore').scrollIntoView({behavior:'smooth'})}
function questionById(id){return(siteData.quiz&&siteData.quiz.questions||[]).find(q=>q.id===id)}
function questionSelect(q,options){const label=content.localize(q.label),any=content.localize(q.anyLabel);return`<label>${esc(label)}<select id="quiz-${esc(q.id)}">${any?`<option value="">${esc(any)}</option>`:''}${options.map(o=>`<option value="${esc(o.id)}">${esc(o.label)}</option>`).join('')}</select></label>`}
function buildQuiz(){const filters=PlatformDirectory.getFilterOptions(allPlatforms);const html=(siteData.quiz&&siteData.quiz.questions||[]).map(q=>{if(q.type==='category')return questionSelect(q,filters.categories.map(id=>({id,label:content.categoryLabel(id)})));if(q.type==='language')return questionSelect(q,filters.languages.map(id=>({id,label:content.languageLabel(id)})));if(q.type==='choice')return questionSelect(q,(q.options||[]).map(o=>({id:o.id,label:content.localize(o.label)})));return''}).join('');$('quizForm').innerHTML=`<div class="quiz-grid">${html}</div><button class="btn btn-primary" id="runQuiz" type="button">${esc(content.localize(siteData.quiz.showResultsLabel)||getText('showResults'))}</button>`;$('quizResults').innerHTML='';$('runQuiz').onclick=runQuiz}
function quizValue(id){const el=$(`quiz-${id}`);return el?el.value:''}
function runQuiz(){const cat=quizValue('category'),lang=quizValue('language'),wantFree=quizValue('free')==='yes',wantCert=quizValue('certificate')==='yes';const ranked=allPlatforms.map(p=>{let points=10,max=10;if(cat){max+=40;if(p.categoryId===cat)points+=40}if(lang){max+=25;if((p.languageIds||[]).includes(lang))points+=25}if(wantFree){max+=15;if(p.hasFreeContent)points+=15}if(wantCert){max+=10;if(p.certificateAvailable)points+=10}return{p,pct:Math.round(points/max*100)}}).sort((a,b)=>b.pct-a.pct).slice(0,3);$('quizResults').innerHTML=`<div class="quiz-results"><h3>${esc(content.localize(siteData.quiz.resultsTitle)||getText('quizResults'))}</h3>${ranked.map((r,i)=>`<a class="match-card" href="${detailUrl(r.p)}"><span>${i+1}</span><strong>${esc(nameFor(r.p))}</strong><b>${r.pct}% ${esc(content.localize(siteData.quiz.matchLabel)||getText('match'))}</b></a>`).join('')}</div>`}
function buildPath(){
  const paths=siteData.quiz&&siteData.quiz.learningPaths||{},guide=siteData.quiz&&siteData.quiz.roadmapGuide||{},stageLabels=siteData.quiz&&siteData.quiz.pathStageLabels||[],goals=Object.entries(paths),builder=$('pathBuilder'),results=$('pathResults');
  let selectedGoal=goals[0]?goals[0][0]:'';
  const goalCards=goals.map(([id,value],index)=>{
    const stages=Array.isArray(value.stages)?value.stages:[],platformCount=new Set(stages.flat()).size,selected=id===selectedGoal,description=content.localize(value.description);
    return `<button class="path-goal-card${selected?' active':''}" type="button" data-path-goal="${esc(id)}" aria-pressed="${selected}"><span class="path-goal-number">${String(index+1).padStart(2,'0')}</span><span class="path-goal-copy"><strong>${esc(content.localize(value.label))}</strong><small>${esc(description)}</small><em>${stages.length} ${esc(getText('stage'))} · ${platformCount} ${esc(getText('platformsAvailable'))}</em></span><span class="path-goal-check" aria-hidden="true">✓</span></button>`;
  }).join('');
  builder.innerHTML=`<div class="path-builder-shell"><div class="path-builder-heading"><div><span class="path-builder-kicker">${esc(getText('pathGoal'))}</span><h3>${esc(getText('buildPath'))}</h3></div><span class="path-builder-count">${goals.length}</span></div><div class="path-goal-grid">${goalCards}</div><button class="btn btn-primary path-generate-btn" id="generatePath" type="button" ${selectedGoal?'':'disabled'}><span data-icon="path" aria-hidden="true"></span><span>${esc(getText('generatePath'))}</span><b aria-hidden="true">→</b></button></div>`;
  results.innerHTML='';
  const selectGoal=id=>{
    selectedGoal=id;
    builder.querySelectorAll('[data-path-goal]').forEach(card=>{const active=card.dataset.pathGoal===id;card.classList.toggle('active',active);card.setAttribute('aria-pressed',String(active))});
  };
  builder.querySelectorAll('[data-path-goal]').forEach(card=>card.onclick=()=>selectGoal(card.dataset.pathGoal));
  $('generatePath').onclick=()=>{
    const entry=paths[selectedGoal],stages=entry&&Array.isArray(entry.stages)?entry.stages:[],goalLabel=entry?content.localize(entry.label):'',guideSteps=Array.isArray(guide.steps)?guide.steps:[],flow=Array.isArray(guide.flow)?guide.flow:[];
    const guideHtml=`<aside class="path-usage-guide"><div class="path-usage-heading"><span>🧭</span><div><h4>${esc(content.localize(guide.title))}</h4><p>${esc(content.localize(guide.subtitle))}</p></div></div><div class="path-usage-steps">${guideSteps.map((step,i)=>`<div><b>${i+1}</b><span>${esc(content.localize(step))}</span></div>`).join('')}</div><div class="path-usage-flow">${flow.map((step,i)=>`<span>${esc(content.localize(step))}${i<flow.length-1?'<b aria-hidden="true">→</b>':''}</span>`).join('')}</div></aside>`;
    const steps=stages.map((ids,i)=>{
      const platforms=ids.map(platformById).filter(Boolean),stageLabel=content.localize(stageLabels[i]||{});
      const cards=platforms.map(p=>`<a class="path-platform-card" href="${detailUrl(p)}"><span class="path-platform-logo">${logoHtml(p,nameFor(p))}</span><span class="path-platform-copy"><strong>${esc(nameFor(p))}</strong><small>${esc(content.categoryLabel(p.categoryId))}</small></span><span class="path-platform-action">${esc(getText('details'))} <b aria-hidden="true">↗</b></span></a>`).join('');
      const first=platforms[0],startAction=first?`<a class="path-stage-action" href="${detailUrl(first)}">${esc(content.localize(guide.startStage))} <b aria-hidden="true">→</b></a>`:'';
      return `<article class="path-step-card"><div class="path-step-marker"><span>${i+1}</span>${i<stages.length-1?'<i class="path-step-connector" aria-hidden="true"></i>':''}</div><div class="path-step-content"><div class="path-step-heading"><div><small>${esc(getText('stage'))} ${i+1}</small><strong>${esc(stageLabel)}</strong></div>${i===0?`<span class="path-start-badge">${esc(content.localize(guide.startHere))}</span>`:''}</div><p class="path-stage-note">${esc(content.localize(guide.platformNote))}</p><div class="path-stage-platforms">${cards}</div>${startAction}</div></article>`;
    }).join('');
    results.innerHTML=`<div class="path-roadmap"><div class="path-roadmap-head"><span class="path-roadmap-icon" data-icon="path" aria-hidden="true"></span><div><small>${esc(getText('pathTitle'))}</small><h3>${esc(goalLabel)}</h3></div><b>${stages.length} ${esc(getText('stage'))}</b></div>${guideHtml}<div class="path-roadmap-track">${steps}</div></div>`;
    results.scrollIntoView({behavior:'smooth',block:'nearest'});
  };
}
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem(STORAGE.theme,theme)}catch(_){}const button=$('themeToggle');if(button)button.textContent=content.icon(theme==='dark'?'themeLight':'themeDark')}
function initTheme(){let saved;try{saved=localStorage.getItem(STORAGE.theme)}catch(_){}setTheme(saved||(window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'))}
function changeLang(lang){setLang(lang);SiteRuntime.applyDocument(document,content,'explore');renderPlatformCloud();renderQuickFilters();hydrateFilterOptions();rerender();const url=new URL(location.href);url.searchParams.set('lang',currentLang);history.replaceState(null,'',url)}
function bindEvents(){[els.filterLang,els.filterCategory,els.filterPricing,els.filterVerification,els.filterFree,els.filterCert,els.sort].forEach(el=>el&&el.addEventListener('change',renderDirectory));els.search.addEventListener('input',()=>{els.heroSearch.value=els.search.value;renderDirectory()});els.heroSearch.addEventListener('input',()=>{els.search.value=els.heroSearch.value;renderDirectory()});$('resetFilters').onclick=resetFilters;$('langSwitcher').onchange=e=>changeLang(e.target.value);$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>{activeTab=btn.dataset.tab;document.querySelectorAll('.tab-btn').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});renderDirectory()});$('quickFilterChips').onclick=e=>{const b=e.target.closest('[data-search-category]');if(!b)return;activeTab='all';els.filterCategory.value=b.dataset.searchCategory;renderDirectory();document.querySelector('#explore').scrollIntoView({behavior:'smooth'})};els.categoryGrid.onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;activeTab='all';els.filterCategory.value=b.dataset.category;renderDirectory();document.querySelector('#explore').scrollIntoView({behavior:'smooth'})};document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){e.preventDefault();const id=a.dataset.id;if(a.dataset.action==='favorite')toggleFavorite(id);if(a.dataset.action==='compare')toggleCompare(id);if(a.dataset.action==='share')sharePlatform(id)}const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close);if(e.target.classList.contains('modal'))closeModal(e.target.id)});$('heroQuizBtn').onclick=()=>{buildQuiz();openModal('quizModal')};$('heroCompareBtn').onclick=$('navCompare').onclick=$('compareNow').onclick=()=>{buildCompareTable();openModal('compareModal')};$('clearCompare').onclick=()=>{setCompare(new Set());rerender()};$('randomBtn').onclick=()=>{const list=visiblePlatforms().length?visiblePlatforms():allPlatforms;if(list.length)location.href=detailUrl(list[Math.floor(Math.random()*list.length)])};$('pathBtn').onclick=()=>{buildPath();openModal('pathModal')};document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();els.heroSearch.focus()}if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))})}
function registerPWA(){if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));const installBtn=$('installBtn');if(!installBtn)return;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.hidden=true}else showToast(getText('installed'))}}
async function init(){const params=new URLSearchParams(location.search);try{siteData=await DataLoader.loadSiteData();initContent(siteData);setLang(resolveInitialLanguage(params.get('lang'),content.rawSetting('defaultLanguage')||'en'),{persist:false});SiteRuntime.applyDocument(document,content,'explore');allPlatforms=siteData.platforms.map(PlatformCore.normalizeStaticPlatform);initTheme();migrateComparisonStorage();renderPlatformCloud();renderQuickFilters();hydrateFilterOptions();const initialQuery=applyInitialSearch(params);rerender();bindEvents();if(params.get('finder')==='1'){buildQuiz();openModal('quizModal')}registerPWA();focusInitialSearchResults(initialQuery);if(!initialQuery)focusInitialExploreResults(params)}catch(err){console.error(err);if(els.grid){els.grid.textContent=getText('errorLoading')||'Unable to load content'}}}
document.addEventListener('DOMContentLoaded',init);

async function initInlineEditorApp(){
  if(!globalThis.DunyaInlineEditorRequested)return;
  await (globalThis.DunyaInlineEditorReady||Promise.resolve(false));
  if(typeof InlineEditor==='undefined'||!InlineEditor.isEditRequested(location))return;
  for(let i=0;i<100&&(!siteData||!content);i++)await new Promise(resolve=>setTimeout(resolve,25));
  if(!siteData||!content)return;
  inlineEditor=InlineEditor.create({document,location,data:siteData,content,onDataChange(next){
    siteData=next;initContent(siteData);setLang(currentLang);allPlatforms=siteData.platforms.map(PlatformCore.normalizeStaticPlatform);
    SiteRuntime.applyDocument(document,content,'explore');hydrateFilterOptions();renderQuickFilters();renderPlatformCloud();rerender();
    setTimeout(()=>inlineEditor&&inlineEditor.refreshTargets(),0);
  }});
  await inlineEditor.init();
}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',()=>initInlineEditorApp().catch(err=>console.error(err)));
